global:
  scrape_interval: 3s  # Частота опроса метрик

scrape_configs:
  - job_name: 'spring-boot-application'
    static_configs:
      - targets: ['localhost:8090']
    metrics_path: '/actuator/prometheus'
